name: cockroach-operator

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v7
        with:
          script: |
            return context.repo.repo
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/lKinderBueno/cockroach-operator
          VERSION=v2.13.0
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - run: go version
      - name: Clone cockroach-operator at tag
        run: git clone --single-branch --branch $version https://github.com/lKinderBueno/cockroach-operator.git
        env:
          version: ${{ steps.prep.outputs.version }}
      - name: Build amd64 version
        run: cd cockroach-operator && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cockroach-operator-amd64 -v cmd/cockroach-operator/*.go
      - name: Build arm64 version
        run: cd cockroach-operator && CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o cockroach-operator-arm64 -v cmd/cockroach-operator/*.go
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/jrcichra/cockroach-operator:buildcache
          cache-to: type=registry,ref=ghcr.io/jrcichra/cockroach-operator:buildcache,mode=max
          labels: |
            org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
            org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
